language: cpp
compiler: gcc
script: make && make test

notifications:
  email:
    recipients:
      - bdwolfe@gcc.edu
    on_success: always   # default: change
    on_failure: always  # default: always

before_install:
  - pip install --user cpp-coveralls
script:
  - ./configure --enable-gcov && make && make check
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
