language: cpp
compiler: gcc
script: make && make test && make coverage

notifications:
  email:
    recipients:
      - bdwolfe@gcc.edu
    on_success: always   # default: change
    on_failure: always  # default: always
