language: cpp
compiler: gcc
script: make && make test

notifications:
  email:
    recipients:
      - bdwolfe@gcc.edu
    on_success: always   # default: change
    on_failure: always  # default: always

env:
  global:
    - CC_TEST_REPORTER_ID=3a0fdc8389069adb2c6f242621a0904bed8bef5b797586980f276795d18e3b83
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
